version: "3.8"

services:
  web:
    image: your_image
    secrets:
      - google_credentials
    environment:
      - GOOGLE_CREDENTIALS_FILE=/etc/secrets/designova-454205-6856ed361431.json

secrets:
  google_credentials:
    external: true
